#!/bin/bash
# Quick Start Guide for Running Tests

echo "=================================================="
echo "Selenium MCP Project - Login and Add to Cart Test"
echo "=================================================="
echo ""

# Option 1: Run with Maven (Recommended for Java)
echo "Option 1: Running Java Test with Maven..."
cd "C:\Users\Aryen\IdeaProjects\TryAI"
echo "Command: mvn clean test"
echo ""
echo "This will:"
echo "✓ Clean previous builds"
echo "✓ Compile the project"
echo "✓ Launch Chrome browser"
echo "✓ Navigate to Rahul Shetty Academy login page"
echo "✓ Sign in with provided credentials"
echo "✓ Find and add iPhone X to cart"
echo "✓ Navigate to checkout"
echo "✓ Verify product in cart"
echo ""

# Option 2: Run Python version
echo "Option 2: Running Python Test (Faster alternative)..."
echo "Command: python run_test.py"
echo ""
echo "This will execute the same test flow using Python/Selenium"
echo ""

echo "=================================================="
echo "Test Credentials"
echo "=================================================="
echo "URL: https://rahulshettyacademy.com/loginpagePractise/"
echo "Username: rahulshettyacademy"
echo "Password: learning"
echo "Role: User"
echo ""

echo "=================================================="
echo "To Run Tests:"
echo "=================================================="
echo ""
echo "1. For Java/TestNG:"
echo "   cd C:\Users\Aryen\IdeaProjects\TryAI"
echo "   mvn clean test"
echo ""
echo "2. For Python:"
echo "   python run_test.py"
echo ""
echo "3. For Standalone Java:"
echo "   mvn clean compile test-compile"
echo "   mvn exec:java"
echo ""
